### ISSUE TITLE
Multi-cycle Path

### ISSUE THREAD

**Issue by seferbey** [pulp-platform/fpnew#16]
Hi,

Is there any multi-cycle path in the design? Critical paths for some instructions are very long.

Thanks.

**Comment by stmach** [comment]
Hello,
there is no explicit need to set multi-cycle paths in the design. However, depending on your target technology, timing constraints and the configuration of formats and operations, it might be necessary to insert pipeline registers into the larger operations. The number of registers is specified in the `PipeRegs` field of the `Implementation` parameter, please refer to the documentation in [`docs/README.md`](https://github.com/pulp-platform/fpnew/blob/develop/docs/README.md) for further information about the parameters.
Also note that the generated registers are inserted at predefined locations and are not optimally placed, thus you should use the retiming functionality of your synthesis tool to move them to more optimal locations. If retiming is not available, the `DISTRIBUTED` strategy yields best results.
